# Site settings
title: James Buck
email: jcebuck@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Computer science graduate with a passion for technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jamesbuck.me" # the base hostname & protocol for your site
username: jcebuck

# Build settings
markdown: kramdown
highlighter: rouge